name: Check Branch Name

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch

jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Branch Naming Convention
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Current branch: $BRANCH_NAME"
          
          # Allow main branch
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "Branch name '$BRANCH_NAME' is valid."
            exit 0
          fi

          # Define your naming convention regex here
          if [[ ! "$BRANCH_NAME" =~ ^CBIN1B1-[A-Za-z]+-[A-Za-z0-9_-]+$ ]]; then
            echo "Branch name '$BRANCH_NAME' does not follow the naming convention!"
            echo "Expected format: <team-name>/<member-name-internshipId>/<task-type>/<description>"
            echo "Examples:CBIN1B1-sivacbin0-java-task1"
            exit 1
          fi
          echo "Branch name '$BRANCH_NAME' is valid."
