name: Create Task Branches

on:
  workflow_dispatch:  # Allows manual triggering from the Actions tab.

jobs:
  create-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Branches for Students
        run: |
          STUDENTS=("student1" "student2" "student3" "student4" "student5")  # List all student usernames
          TASK_NAME="new_task"  # Define your task name
          for STUDENT in "${STUDENTS[@]}"; do
            BRANCH_NAME="cb-in1-b1/$STUDENTId/java/$TASK_NAME"
            git checkout -b "$BRANCH_NAME"
            git push origin "$BRANCH_NAME"
            echo "Created branch: $BRANCH_NAME"
            git checkout main  # Switch back to the main branch
          done
