name: Create Branch and Task

on:
  workflow_dispatch:  # This allows you to run the workflow manually
  # You can also add more triggers like push or pull_request if needed

jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Git configuration
      - name: Set up Git credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Define branch name
      - name: Define Branch Name
        id: vars
        run: echo "BRANCH_NAME=CBIN1B1-student1-html-task1" >> $GITHUB_ENV  # Example branch name

      # Create and push the branch
      - name: Create and Push Branch
        run: |
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
